name: Build Zed for Windows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
  

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Toolchain
      run: rustup target add wasm32-wasi

    - name: Clone Source Code
      run: |
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git clone https://github.com/zed-industries/zed -b main zed

    - name: Build Executable
      run: |
        cd zed
        cargo build --release

    - name: Compile Setup Wizzard
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: Zed_Wizzard.iss
        options: /O+        
        
    - name: Upload Setup Wizzard
      uses: actions/upload-artifact@main
      with:
        name: setup
        path: zed_setup.exe
        

  release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download Release Folder
        uses: actions/download-artifact@v4
        with:
          name: setup
          path: zed/target/release

      - name: Setup Git Environment
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Generate Release Tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d")"
          echo "::set-output name=release_date::$(date +"%Y.%m.%d")"     
          
      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_date }} Zed Windows
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: zed/target/release/zed.exe          
